version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      # Group all minor and patch updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Group all major updates together (more risky, so separate)
      major:
        patterns:
          - "*"
        update-types:
          - "major"
    reviewers:
      - "MarcusCJH"
    assignees:
      - "MarcusCJH"
    commit-message:
      prefix: "chore"
      include: "scope"
